### DISCUSSION TITLE
Testing of v2.0.0a1 (archive migration)

### DISCUSSION THREAD

**Discussion by chrisjsewell** [aiidateam/aiida-core#5407] [General]
Similar to #5379, this is intended for collecting reports on archive migrations.

Steps:

- install aiida-core `develop` into an virtual environment
- `pip install process-plot` (or `pipx`)
- Report origin and size of initial archive
- `pplot exec -i 0.5 -c screen --title "Archive migrate" "/path/to/bin/python -m aiida archive migrate -f -v info /path/to/input.aiida test.aiida"`
   - Report stdout and generated plot
   - (note, "legacy" migrations have to read the full database, i.e. `data.json`, into memory, but future migrations on `db.sqlite3` will not require this, so the memory profile will be a lot lower)
- `verdi archive info --statistics test.aiida`
- `verdi quicksetup --profile test_import`
- `pplot exec -i 0.5 -c screen --title "Archive import" "/path/to/bin/python -m aiida -p test_import archive import -v info test.aiida"`
   - Report stdout and generated plot 
- `verdi -p test_import storage info --statistics`

**Comment by chrisjsewell** [comment]
Example:

- 2D-materials Archive: https://archive.materialscloud.org/record/2020.158
- Initial size (after download): 979.5 Mb

Migration:

```
PPLOT INFO: Output files will be written to: /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/pplot_out, with basename: 20220304202449
PPLOT INFO: Staring command: ['/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py38-pre-commit/bin/python', '-m', 'aiida', 'archive', 'migrate', '-f', '-v', 'info', '/Users/chrisjsewell/Downloads/two_dimensional_database.aiida', 'test.aiida']
PPLOT INFO: Running process as PID: 20534
Report: Legacy migrations required from zip format
Report: Extracting data.json ...
Report: Legacy migration pathway: 0.9 -> 0.10 -> 0.11 -> 0.12
Performing migrations: 0.11 -> 0.12      100.0%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3
Report: legacy '0.12' -> 'main_0000' conversion required
Report: Initialising new archive...
Converting repo                          100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 631367/631367
Report: Unique repository files written: 205805
Report: Converting DB to SQLite
Adding Users                             100.0%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6
Adding Computers                         100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14
Adding Groups                            100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16
Adding Nodes                             100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113078/113078
Adding Links                             100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 164968/164968
Adding Group-Nodes                       100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4453/4453
Report: Performing SQLite migrations:
Report: - main_0000 -> main_0000a
Report: - main_0000a -> main_0000b
Report: - main_0000b -> main_0001
Report: Finalising the migration ...
Success: migrated the archive to version 'main_0001'
PPLOT INFO: Total run time: 0 hour(s), 05 minute(s), 24.793173 second(s)
PPLOT INFO: Plotting results to: pplot_out/20220304202449.png
PPLOT SUCCESS!
```

![20220304202449](https://user-images.githubusercontent.com/2997570/156842559-8c5384b8-5ae0-432a-8628-d86d523b18c2.png)

- Migrated size: 879.4 Mb

Archive statistics:

```yaml
metadata:
  export_version: main_0001
  aiida_version: 2.0.0a1
  conversion_info:
  - Converted from version 0.3 to 0.4 with AiiDA v1.4.1
  - Converted from version 0.4 to 0.5 with AiiDA v1.4.1
  - Converted from version 0.5 to 0.6 with AiiDA v1.4.1
  - Converted from version 0.6 to 0.7 with AiiDA v1.4.1
  - Converted from version 0.7 to 0.8 with AiiDA v1.4.1
  - Converted from version 0.8 to 0.9 with AiiDA v1.4.1
  - Converted from version 0.9 to 0.10 with AiiDA v2.0.0a1
  - Converted from version 0.10 to 0.11 with AiiDA v2.0.0a1
  - Converted from version 0.11 to 0.12 with AiiDA v2.0.0a1
  - Converted from version 0.12 to main_0000 with AiiDA v2.0.0a1
  - Converted from version main_0000 to main_0001 with AiiDA v2.0.0a1
  mtime: '2022-03-04T20:24:51.899366'
  compression: 6
  creation_parameters: {}
  key_format: sha256
entities:
  Users:
    count: 6
    emails:
    - aiida@theossrv2.epfl.ch
    - aiida@theossrv5.epfl.ch
    - davide.campi@epfl.ch
    - giovanni.pizzi@epfl.ch
    - ivano.castelli@epfl.ch
    - nicolas.mounet@epfl.ch
  Computers:
    count: 14
    labels:
    - bellatrix
    - brisi
    - 'daint (Imported #1)'
    - daint-gpu
    - daint-mc
    - daint_aprun
    - daint_mc
    - 'daint_mc (Imported #0)'
    - daint_old
    - dora
    - dora_aprun
    - localhost
    - theospc14-direct_
    - theospc27slurm
  Nodes:
    count: 113078
    node_types:
    - data.core.array.ArrayData.
    - data.core.array.bands.BandsData.
    - data.core.array.kpoints.KpointsData.
    - data.core.array.trajectory.TrajectoryData.
    - data.core.cif.CifData.
    - data.core.code.Code.
    - data.core.dict.Dict.
    - data.core.folder.FolderData.
    - data.core.remote.RemoteData.
    - data.core.singlefile.SinglefileData.
    - data.core.structure.StructureData.
    - data.core.upf.UpfData.
    - data.forceconstants.ForceconstantsData.
    - process.calculation.calcfunction.CalcFunctionNode.
    - process.calculation.calcjob.CalcJobNode.
    process_types:
    - aiida.calculations:codtools.ciffilter
    - aiida.calculations:quantumespresso.matdyn
    - aiida.calculations:quantumespresso.ph
    - aiida.calculations:quantumespresso.pw
    - aiida.calculations:quantumespresso.q2r
  Groups:
    count: 16
    type_strings:
    - core
  Comments:
    count: 0
  Logs:
    count: 0
  Links:
    count: 164968
repository:
  objects:
    count: 205805
```

Import:

```
PPLOT INFO: Output files will be written to: /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/pplot_out, with basename: 20220304204621
PPLOT INFO: Staring command: ['/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py38-pre-commit/bin/python', '-m', 'aiida', '-p', 'test_import', 'archive', 'import', '-v', 'info', 'test.aiida']
PPLOT INFO: Running process as PID: 26601
Report: starting import: test.aiida
Report: Parameters
-------------------------------  ----------------
Archive                          test.aiida
New Node Extras                  keep
Merge Node Extras (in database)  (k)eep
Merge Node Extras (in archive)   do (n)ot create
Merge Node Extras (in both)      (l)eave existing
Merge Comments                   leave
Computer Authinfos               exclude

Report: Adding 6 new user(s)
Adding new user(s)                       100.0%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6
Report: Adding 14 new computer(s)
Adding new computer(s)                   100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14
Report: Collecting Node(s) ...
Report: Adding 113078 new node(s)
Adding new node(s)                       100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113078/113078
Report: Gathering existing 'create' Link(s)
Processing 'create' Link(s)              100.0%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 65426/65426
Report: Added 65426 new 'create' Link(s)
Report: Gathering existing 'input_calc' Link(s)
Processing 'input_calc' Link(s)          100.0%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99542/99542
Report: Added 99542 new 'input_calc' Link(s)
Report: Adding 16 new group(s)
Adding new group(s)                      100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16
Report: Adding 4453 Node(s) to new Group(s)
Adding new group_node(s)                 100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4453/4453
Report: Created new import Group: PK=17, label=20220304-204817
Adding all Node(s) to the import Group   100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113078/113078
Collecting archive Node file keys        100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113078/113078
Report: Checking keys against repository ...
Report: Adding 205805 new repository files
Adding archive files to repository       100.0%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 205805/205805
Report: Committing transaction to database...
Success: imported archive test.aiida
PPLOT INFO: Total run time: 0 hour(s), 05 minute(s), 27.168418 second(s)
PPLOT INFO: Plotting results to: pplot_out/20220304204621.png
PPLOT SUCCESS!
```
![20220304204621](https://user-images.githubusercontent.com/2997570/156842758-11914b62-7f79-4c45-970d-a7d8fcee7b99.png)

Import statistics:

```yaml
entities:
  Users:
    count: 7
    emails:
    - a@b.com
    - aiida@theossrv2.epfl.ch
    - aiida@theossrv5.epfl.ch
    - davide.campi@epfl.ch
    - giovanni.pizzi@epfl.ch
    - ivano.castelli@epfl.ch
    - nicolas.mounet@epfl.ch
  Computers:
    count: 14
    labels:
    - bellatrix
    - brisi
    - 'daint (Imported #1)'
    - daint-gpu
    - daint-mc
    - daint_aprun
    - daint_mc
    - 'daint_mc (Imported #0)'
    - daint_old
    - dora
    - dora_aprun
    - localhost
    - theospc14-direct_
    - theospc27slurm
  Nodes:
    count: 113078
    node_types:
    - data.core.array.ArrayData.
    - data.core.array.bands.BandsData.
    - data.core.array.kpoints.KpointsData.
    - data.core.array.trajectory.TrajectoryData.
    - data.core.cif.CifData.
    - data.core.code.Code.
    - data.core.dict.Dict.
    - data.core.folder.FolderData.
    - data.core.remote.RemoteData.
    - data.core.singlefile.SinglefileData.
    - data.core.structure.StructureData.
    - data.core.upf.UpfData.
    - data.forceconstants.ForceconstantsData.
    - process.calculation.calcfunction.CalcFunctionNode.
    - process.calculation.calcjob.CalcJobNode.
    process_types:
    - aiida.calculations:codtools.ciffilter
    - aiida.calculations:quantumespresso.matdyn
    - aiida.calculations:quantumespresso.ph
    - aiida.calculations:quantumespresso.pw
    - aiida.calculations:quantumespresso.q2r
  Groups:
    count: 17
    type_strings:
    - core
    - core.import
  Comments:
    count: 0
  Logs:
    count: 0
  Links:
    count: 164968
repository:
  SHA-hash algorithm: sha256
  Compression algorithm: zlib+1
  Packs: 0
  Objects:
    unpacked: 205805
    packed: 0
  Size (MB):
    unpacked: 4002.8430767059326
    packed: 0.0
    other: 0.01171875
```

**Comment by giovannipizzi** [comment]
Thanks to Valeria, here's a list of all .aiida files on the Materials Cloud Archive with links.
I won't manage to check them myself in the upcoming days, so I put the file here and maybe one person can take care of writing a script and testing them all? (On some big machines maybe, since some might be big?)

[mc_archive_aiida_files_2022_03_17.txt](https://github.com/aiidateam/aiida-core/files/8314485/mc_archive_aiida_files_2022_03_17.txt)

**Comment by mbercx** [comment]
Found an issue while migrating:

https://archive.materialscloud.org/record/file?record_id=894&filename=export_discovery_cof_22Feb21.aiida

Output:

```console
Report: Legacy migrations required from zip format
Report: Extracting data.json ...
Report: Legacy migration pathway: 0.10 -> 0.11 -> 0.12
                                                               Report: legacy '0.12' -> 'main_0000' conversion required
Report: Initialising new archive...
                                                                           Report: Unique repository files written: 263897
Report: Converting DB to SQLite
                                                                      Report: Performing SQLite migrations:
Report: - main_0000 -> main_0000a
Report: - main_0000a -> main_0000b
Report: - main_0000b -> main_0001
Report: Finalising the migration ...
Critical: failed to migrate the archive file (use `--verbosity DEBUG` to see traceback): RuntimeError:File size unexpectedly exceeded ZIP64 limit
```

**Reply by chrisjsewell** [reply]
Heya, yeh so basically here we need to set `force_zip64=True` on opening the zip 
see https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.open, and specifically: https://github.com/python/cpython/blob/5101d97d0b13425ccc5ed37abfabb07701db81fe/Lib/zipfile.py#L1192-L1195

**Reply by chrisjsewell** [reply]
The change would need to go here: https://github.com/aiidateam/archive-path/blob/b7d48bcf73ad45978c09eefd081086a29c6aefeb/archive_path/zip_path.py#L315
but I'm not sure what the implications of always setting this to `True` (note this means you have at least one single file that is bigger than 2Gb!)

**Reply by giovannipizzi** [reply]
According to the analysis that @yakutovicha did in the past, it seemed OK to always set zip64 to True: https://github.com/aiidateam/aiida-core/issues/1617 (this was, however, for a slightly different zip64-related flag)

**Reply by chrisjsewell** [reply]
@mbercx, this should fix it: https://github.com/aiidateam/aiida-core/pull/5498
although the URL you gave above results in a "Page not found", so I cannot check it myself

**Reply by mbercx** [reply]
Worked like a charm!

```console
$ verdi archive migrate export_discovery_cof_22Feb21.aiida test2-export_discovery_cof_22Feb21.aiida 2>&1 | tee -a test2-migrate.log
Report: Legacy migrations required from zip format
Report: Extracting data.json ...
Report: Legacy migration pathway: 0.10 -> 0.11 -> 0.12
                                                               Report: legacy '0.12' -> 'main_0000' conversion required
Report: Initialising new archive...
                                                                           Report: Unique repository files written: 263897
Report: Converting DB to SQLite
                                                                      Report: Performing SQLite migrations:
Report: - main_0000 -> main_0000a
Report: - main_0000a -> main_0000b
Report: - main_0000b -> main_0001
Report: Finalising the migration ...
Success: migrated the archive to version 'main_0001'
```

**Reply by chrisjsewell** [reply]
Cheers! Yeh I guess it would be good to also now check that it can be read etc

**Reply by mbercx** [reply]
Running an import now 👍

**Reply by mbercx** [reply]
```console
$ verdi archive import test2-export_discovery_cof_22Feb21.aiida -G test2
Report: starting import: test2-export_discovery_cof_22Feb21.aiida
Report: Parameters
-------------------------------  ----------------------------------------
Archive                          test2-export_discovery_cof_22Feb21.aiida
New Node Extras                  keep
Merge Node Extras (in database)  (k)eep
Merge Node Extras (in archive)   do (n)ot create
Merge Node Extras (in both)      (l)eave existing
Merge Comments                   leave
Computer Authinfos               exclude   

Report: Adding 1 new user(s)
Report: Adding 11 new computer(s)
Report: Collecting Node(s) ...
Report: Adding 586312 new node(s)
Report: Adding 242376 new log(s)
Report: Gathering existing 'create' Link(s)
Report: Added 283978 new 'create' Link(s)  
Report: Gathering existing 'return' Link(s)
Report: Added 175378 new 'return' Link(s)  
Report: Gathering existing 'input_calc' Link(s)
Report: Added 496716 new 'input_calc' Link(s)
Report: Gathering existing 'input_work' Link(s)
Report: Added 451147 new 'input_work' Link(s)
Report: Gathering existing 'call_calc' Link(s)
Report: Added 123453 new 'call_calc' Link(s)
Report: Gathering existing 'call_work' Link(s)
Report: Added 50808 new 'call_work' Link(s)
Report: Adding 632 new group(s)
Report: Adding 12586 Node(s) to new Group(s)
Report: Using existing import Group: PK=64, label=test2
Report: Checking keys against repository ...
Report: Skipping 1 existing repository files
Report: Adding 263896 new repository files 
Report: Committing transaction to database...
Success: imported archive test2-export_discovery_cof_22Feb21.aiida
```

**Reply by mbercx** [reply]
Also tried querying, loading nodes etc. Seems ok!

**Comment by mbercx** [comment]
More trouble in paradise:

https://archive.materialscloud.org/record/file?record_id=1120&filename=gamma_Fe.aiida

Here is the output:

```console
Report: Legacy migrations required from zip format
Report: Extracting data.json ...
Report: Legacy migration pathway: 0.10 -> 0.11 -> 0.12
                                                               Report: legacy '0.12' -> 'main_0000' conversion required
Report: Initialising new archive...
Critical: failed to migrate the archive file (use `--verbosity DEBUG` to see traceback): error:Error -3 while decompressing data: invalid code lengths set
```

**Reply by chrisjsewell** [reply]
@mbercx it would be helpful if you used `--verbosity DEBUG` 😉

**Reply by mbercx** [reply]
Haha, fair. I'm just running all of them first, will rerun with the flag afterwards 😅

**Reply by chrisjsewell** [reply]
👍

**Reply by mbercx** [reply]
Hmm, now one of the migrations seems stuck. Let me check if it is still doing anything.

Either way, I'll try the problematic migration above again with `--verbosity DEBUG` separately.

**Reply by mbercx** [reply]
Full output of running with `--verbosity DEBUG`:

```
$ verdi archive migrate gamma_Fe.aiida test2-gamma_Fe.aiida --verbosity DEBUG 2>&1 | tee -a log_gamma_Fe_mig.log
Report: Legacy migrations required from zip format
Report: Extracting data.json ...
Report: Legacy migration pathway: 0.10 -> 0.11 -> 0.12
Performing migrations: 0.11 -> 0.12      100.0%|██████████| 2/2Report: legacy '0.12' -> 'main_0000' conversion required
Report: Initialising new archive...

Converting repo                           39.8%|███▉      | 6060/15230
Traceback (most recent call last):
  File "/home/aiida/.virtualenvs/aiida-super/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/aiida/.virtualenvs/aiida-super/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/aiida/.virtualenvs/aiida-super/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/aiida/.virtualenvs/aiida-super/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.virtualenvs/aiida-super/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.virtualenvs/aiida-super/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aiida/.virtualenvs/aiida-super/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/aiida/envs/aiida-super/code/aiida-core/aiida/cmdline/commands/cmd_archive.py", line 245, in migrate
    archive_format.migrate(input_file, output_file, version, force=force, compression=6)
  File "/home/aiida/envs/aiida-super/code/aiida-core/aiida/tools/archive/implementations/sqlite_zip/main.py", line 110, in migrate
    return migrate(inpath, outpath, version, force=force, compression=compression)
  File "/home/aiida/envs/aiida-super/code/aiida-core/aiida/storage/sqlite_zip/migrator.py", line 216, in migrate
    db_path = perform_v1_migration(inpath, Path(tmpdirname), new_zip, central_dir, is_tar, metadata, data)
  File "/home/aiida/envs/aiida-super/code/aiida-core/aiida/storage/sqlite_zip/migrations/legacy_to_main.py", line 122, in perform_v1_migration
    hashkey = chunked_file_hash(handle, sha256)
  File "/home/aiida/envs/aiida-super/code/aiida-core/aiida/common/hashing.py", line 100, in chunked_file_hash
    chunk = handle.read(chunksize)
  File "/usr/lib/python3.8/zipfile.py", line 940, in read
    data = self._read1(n)
  File "/usr/lib/python3.8/zipfile.py", line 1016, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid code lengths set
```

any ideas?

**Reply by chrisjsewell** [reply]
@mbercx this archive appears to be corrupt.
I downloaded it and tried to just unzip it externally, and got:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/2997570/165297383-ecc43cb1-e87a-43d1-81c8-bbd111b4b072.png">

Perhaps you can also try?

**Comment by mbercx** [comment]
Seems the migration I mentioned [above](https://github.com/aiidateam/aiida-core/discussions/5407#discussioncomment-2629074) is really stuck... Here's the URL to the archive:

https://archive.materialscloud.org/record/file?record_id=1005&filename=export_Nb_KKR-BdG.aiida

I'll try to stop it and rerun with `--verbosity DEBUG` I fear it's a long migration though.

**Reply by mbercx** [reply]
Wait, nvmd 😅 . When I pressed any button in the screen it suddenly is moving again. Seems the progress bar just froze, so ignore this one.

Big archives though, I've been running these migrations for a while now.

**Comment by eimrek** [comment]
Hi, for reference, I'm adding here a report of the SSSP archive import, which is a bit problematic.
The memory usage during the import spikes up to around 15 GB. Our materialscloud machines have 16 GB of RAM, so for this import to work, I have to close other process to prevent a out-of-memory error. This is manageable, so this issue is not urgent.

Archive size: 14 GB

`verdi archive info --detailed`:

```
metadata:
  export_version: main_0001
  aiida_version: 2.0.1
  key_format: sha256
  compression: 6
  ctime: '2022-05-20T16:20:04.505023'
  creation_parameters:
    entities_starting_set: null
    include_authinfos: false
    include_comments: true
    include_logs: true
    graph_traversal_rules:
      input_calc_forward: false
      input_calc_backward: true
      create_forward: true
      create_backward: true
      return_forward: true
      return_backward: false
      input_work_forward: false
      input_work_backward: true
      call_calc_forward: true
      call_calc_backward: true
      call_work_forward: true
      call_work_backward: true
entities:
  Users:
    count: 4
    emails:
    - antimo.marrazzo@epfl.ch
    - gianluca.prandini@epfl.ch
    - ivano.castelli@epfl.ch
    - nicolas.mounet@epfl.ch
  Computers:
    count: 14
    labels:
    - Bellatrix
    - Daint
    - Dora
    - PizDaint
    - PizDaint_XC50
    - Pizdaint
    - aries
    - bellatrix
    - deneb
    - deneb1
    - dora
    - fidis
    - pizdaint
    - theospc6
  Nodes:
    count: 468701
    node_types:
    - data.core.array.ArrayData.
    - data.core.array.bands.BandsData.
    - data.core.array.kpoints.KpointsData.
    - data.core.cif.CifData.
    - data.core.code.Code.
    - data.core.dict.Dict.
    - data.core.folder.FolderData.
    - data.core.remote.RemoteData.
    - data.core.singlefile.SinglefileData.
    - data.core.structure.StructureData.
    - data.core.upf.UpfData.
    - process.calculation.calcfunction.CalcFunctionNode.
    - process.calculation.calcjob.CalcJobNode.
    process_types:
    - aiida.calculations:quantumespresso.ph
    - aiida.calculations:quantumespresso.pw
  Groups:
    count: 600
    type_strings:
    - core
    - core.import
  Comments:
    count: 0
  Logs:
    count: 0
  Links:
    count: 645132
repository:
  objects:
    count: 14184533
```


PPLOT import stdout:

```
PPLOT INFO: Output files will be written to: /home/kristjan/wshare/explore_datasets/standard_sssp_v7/untar/pplot_out, with basename: 20220614221712
PPLOT INFO: Staring command: ['/home/kristjan/opt/anaconda/envs/aiida/bin/python', '-m', 'aiida', '-p', 'test_import', 'archive', 'import', '-v', 'info', 'all_c6_pre-maintain.aiida']
PPLOT INFO: Running process as PID: 55485
Report: starting import: all_c6_pre-maintain.aiida
Report: Parameters
-------------------------------  -------------------------
Archive                          all_c6_pre-maintain.aiida
New Node Extras                  keep
Merge Node Extras (in database)  (k)eep
Merge Node Extras (in archive)   do (n)ot create
Merge Node Extras (in both)      (l)eave existing
Merge Comments                   leave
Computer Authinfos               exclude

Report: Adding 4 new user(s)
Adding new user(s)                       100.0%|██████████| 4/4
Report: Adding 14 new computer(s)
Adding new computer(s)                   100.0%|██████████| 14/14
Report: Collecting Node(s) ...
Report: Adding 468701 new node(s)
Adding new node(s)                       100.0%|██████████| 468701/468701
Report: Gathering existing 'create' Link(s)
Processing 'create' Link(s)              100.0%|██████████| 252929/252929
Report: Added 252929 new 'create' Link(s)
Report: Gathering existing 'input_calc' Link(s)
Processing 'input_calc' Link(s)          100.0%|██████████| 392203/392203
Report: Added 392203 new 'input_calc' Link(s)
Report: Adding 600 new group(s)
Adding new group(s)                      100.0%|██████████| 600/600
Report: Adding 511264 Node(s) to new Group(s)
Adding new group_node(s)                 100.0%|██████████| 511264/511264
Report: Created new import Group: PK=1202, label=20220614-223255
Adding all Node(s) to the import Group   100.0%|██████████| 468701/468701
Collecting archive Node file keys        100.0%|██████████| 468701/468701
Report: Checking keys against repository ...
Report: Skipping 1086011 existing repository files
Report: Adding 13098522 new repository files
Adding archive files to repository       100.0%|██████████| 13098522/13098522
Report: Committing transaction to database...
Success: imported archive all_c6_pre-maintain.aiida
PPLOT INFO: Total run time: 1 day, 2 hour(s), 47 minute(s), 01.987001 second(s)
PPLOT INFO: Plotting results to: pplot_out/20220614221712.png
PPLOT SUCCESS!
```

and the corresponding image:
![20220614221712](https://user-images.githubusercontent.com/8721264/177335860-7809db35-b587-429b-90c9-f7a43795eaa7.png)

(Ignore the straight line, my computer was hibernated during that time.)

The archive file is located on castor, in the container `dev-aiida-repositories/migrated_archives/sssp/sssp.aiida`
