### ISSUE TITLE
conda distribution

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#2550]
It would be good to have an aiida distribution on conda-forge (a lot easier than messing around with homebrew and ports etc).
I see you've created an environment.yml previously #2081 

Here an attached environment.yml that (at least today) works with the `provenance redesign` branch, for a python 3.6 environment, that allows `aiida_core` to be installed (and work) with no dependencies:

    conda env create --file=conda_env_py36_aiida1b1.yaml
    conda activate aiida_1b1
    pip install --no-deps -e .

[conda_env_py36_aiida1b1.txt](https://github.com/aiidateam/aiida_core/files/2917057/conda_env_py36_aiida1b1.txt) (I had to change the extension from yml, for GitHub to accept it)

There was some minor tweaks to versions (see comments), but they don't seem to break anything

**Comment by chrisjsewell** [comment]
On a related note, I use [this script](https://gist.github.com/chrisjsewell/347fd9edd9dff1c06a409bc9634af65c) to spin-up different 'aiida environments',
defined by a yaml config file

**Comment by ltalirz** [comment]
@chrisjsewell you may want to try `conda install -c conda-forge aiida-core` ;-)

Currently, we only have 0.12.2 there and so far I think it is not very well tested.
But the plan is definitely to promote it more - the beauty of conda is that it even allows to install postgresql and rabbitmq (currently not yet added as a dependency but planning to do this).

**Comment by ltalirz** [comment]
Now started looking through your script - thanks for your work, much appreciated!
As soon as the beta1 is out I will prepare the recipe on conda-forge.
Can I count on you for testing / assistance?

**Comment by chrisjsewell** [comment]
@ltalirz perfect I didn't notice that :) yes if you look at my yaml, I have 
postgresql and rabbitmq in there already

> Can I count on you for testing / assistance?

absolutely

**Comment by chrisjsewell** [comment]
aiida-crystal17 is now on [conda-forge](https://anaconda.org/conda-forge/aiida-crystal17) :)

This environment, runs and passes all my tests:

```yaml
name: aiida_cry17_0_4_0_py27
channels:
  - conda-forge
  - bioconda # for chainmap
  - cjs14 # for pgtest
  - defaults
dependencies:
  - aiida-core==0.12.2
  - chainmap==1.0.2
  - aiida-crystal17==0.4.0
  - pytest
  - pytest-timeout
  - pgtest
```

**Comment by ltalirz** [comment]
Very cool!
I'll be updating the docs for aiida 0.12.3 (working on the release now), streamlining the installation instruction and also pointing out the conda-forge alternative.

There are essentially two reasons I didn't yet include postgres as a dependency in the 0.12.2 conda package:
  * conda didn't have an "extras" mechanism, so you are forcing everyone to download it (not sure whether this changed in the meanwhile?)
  * I wasn't quite sure what to tell people on how to run it - of course they can always start it by hand (or we could include scripts to do that) but it seems like you rather want it to be a system service

If you have any thoughts on these issues, I'd be very happy to hear them

**Comment by chrisjsewell** [comment]
> conda "extras" mechanism

Had a little look into it for another package, here's some relevant issues:

  - conda/conda#7502
  - conda/conda#1696
  - conda/conda#2984

> rather want it to be a system service

Yeh I guess like travis's mechanism, would be cool. I leave that to you though!

**Comment by ltalirz** [comment]
Thanks for the hints concerning "extras" - Yes, I could imagine including e.g. an `aiida-core` and `aiida-core.services` package as `outputs`.

> Yeh I guess like travis's mechanism, would be cool. I'll leave that to you though!

So, just that I understand: you currently use postgres and rabbitmq installed via conda and always start it manually? Would you be happy with this solution to start with?

**Comment by chrisjsewell** [comment]
Ok so I've redone my activate_aiida script into a [conda package](https://anaconda.org/cjs14/activate-aiida), which effectively spits the process into two stages:

1. Conda Environment
   1. (first time only) create it from environment.yml
   2. activate environment
   3. (optional, first time only) pip install local development packages (`pip install --no-deps -e .`)  # TODO
   4. (optional) set branches of local development packages
2. AiiDA Environment
   1. start SQL
   2. (first time only) create SQL User & Database
   3. `rabbitmq-server -detached` (aiida_core >= v1)
   4. `reentry scan -r aiida`
   5. (first time only) create AiiDA Database
   6. (first time only) setup verdi tab completion
   7. start aiida daemon
   8. (optional) import common nodes (created by `verdi export created`)

The following example creates and activates a full aiida environment from scratch, 
without having to go through all the steps manually:

conda_environment.yaml:

```yaml
name: aiida_0_12_2_190305
channels:
    - conda-forge
    - cjs14
    - bioconda
    - defaults
dependencies:
    - aiida-core ==0.12.2
    - chainmap ==1.0.2
    - postgresql >=9.4
    - aiida-crystal17 =0.4
    - aiida-quantumespresso ==2.1.1a2
    #- jupyter =1.0
    - activate-aiida
```

aiida_environment.yaml:

```yaml
conda_env: aiida_0_12_2_activate
aiida_version: 0.12
aiida_path: /Users/cjs14/GitHub/aiida-cjs-working/databases/aiida/
db_pgsql:
  path: /Users/cjs14/GitHub/aiida-cjs-working/databases/pgsql/aiida_0_12_2_190305
  user: testuser
  user-password: xxxx  # should handle this more securely
  name: testdb
  port: 5432  
db_aiida:
  path: /Users/cjs14/GitHub/aiida-cjs-working/databases/aiida/aiida_0_12_2_190305
  profile: testprofile
  email: chrisj_sewell@hotmail.com
  first-name: chris
  last-name: sewell
  institution: imperial
import_nodes:
  - common_nodes.zip
git_branches:
  - path: /Users/cjs14/GitHub/aiida-lammps
    branch: master
```

Then run:

```console
>> conda env create --file=conda_environment.yaml
>> conda activate aiida_0_12_2_activate
>> source activate-aiida -c -i aiida_environment.yaml
```

and to stop the daemon and pgsql: `>> deactivate-aiida`

and you can run ` source activate-aiida aiida_environment.yaml`, 
whenever you want to restart the database & daemon.

Some notes:

- the main script is still written in bash, this could probably be ported into python.
  the main sticking point I found though, is parsing environmental variables back to the parent process 
- `verdi daemon configureuser` (in v0.12) doesn't allow the new daemon user to be parsed via an argument, so you have to do it manually.  This is basically the only non-automated bit.
- could also add an `aiida-backup` script
- in your potential `aiida-core.services` it would be nice to include jupyter and load the aiida notebook extension during the conda install.
