### ISSUE TITLE
Node store method excepts for invalid caching configuration files

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3329]
For a configuration file as follows:
```
django:
    default: False
    enabled:
        # - aiida.calculations:quantumespresso.pw
    disabled:
        # - aiida.calculations:templatereplacer
```
the `Node.store()` method will except because the caching configuration parsing in `aiida.manage.caching` will except. It does not deal with the fact that the `enabled` and `disabled` keys can be empty.
