### ISSUE TITLE
Can't provide empty string for the append text in a yaml config file.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#4300]
### Describe the bug

If the `append_text/prepend_text` parameters are set to an empty string `''` (without space) `verdi code setup` would request to provide them and wait for user's input. As a temporarily solution one can use a string with one space.

### Steps to reproduce

Try to setup a computer using the follwing config file:
```yaml
---
label: daint-mc
hostname: daint.cscs.ch
description: Piz Daint supercomputer at CSCS Lugano, Switzerland, multicore partition.
transport: ssh
scheduler: slurm
work_dir: /scratch/snx3000/{username}/aiida_run/
shebang: '#!/bin/bash'
mpirun_command: srun -n {tot_num_mpiprocs}
mpiprocs_per_machine: '36'
prepend_text: ''
append_text: ''
```

### Expected behavior

An empty string should be acceptable.
