### ISSUE TITLE
Docs: code.yml file outdated

### ISSUE THREAD

**Issue by degennar** [aiidateam/aiida-core#5793]
At the [How to run external codes](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_codes.html) page, the suggested `code.yml` file is outdated.

Update the keywords names.

**Comment by sphuber** [comment]
Thanks for the report @degennar . Could you please be a bit specific which version of the documentation and what paragraph you are referring to? The [How to create a Code](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_codes.html#how-to-create-a-code) section of the latest docs seems to be showing the correct structure:
```yaml
label: 'qe-6.3-pw'
description: 'quantum_espresso v6.3'
default_calc_job_plugin: 'quantumespresso.pw'
filepath_executable: '/path/to/code/pw.x'
computer: 'localhost'
prepend_text: |
   module load module1
   module load module2
append_text: ' '
```

Or are you referring to something else?
