### ISSUE TITLE
AIIDA_VERSION was removed from build.json

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#6510]
https://github.com/aiidateam/aiida-core/blob/e91371573a84d4a68d6107f33c392b8718f2f26f/.github/workflows/docker-publish.yml#L72

It cause the problem that aiida version tag not exist in https://github.com/aiidateam/aiida-core/pkgs/container/aiida-core-with-services @danielhollas

**Comment by danielhollas** [comment]
I don't think is makes sense for it to be in `build.json` given that it's only used when making a release. You can take the version from the tag itself by stripping the `v` from the beginning. Annoyingly, github actions don't have any [built-in string manipulation](https://github.com/orgs/community/discussions/26625) so it will have to be a separate step, something like this

```yaml
- id: get-version
  if: ${{ github.ref_type == 'tag'  && startsWith(github.ref_name, 'v') }} 
  run: |
      tag="${{ github.ref_name }}"
      echo "AIIDA_VERSION=${tag#v}" >> $GITHUB_OUTPUT
```

and then use it

```
type=raw,value=aiida-${{ steps.get-version.outputs.AIIDA_VERSION }},enable=${{ github.ref_type == 'tag'  && startsWith(github.ref_name, 'v') }} 
```
